import 'dart:ui';
import 'package:flutter/material.dart';
import '../../core/app_export.dart';

String _appTheme = "primary";

/// Helper class for managing themes and colors.
class ThemeHelper {
  // A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Changes the app theme to [_newTheme].
  void changeTheme(String _newTheme) {
    _appTheme = _newTheme;
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      scaffoldBackgroundColor: appTheme.black900,
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          backgroundColor: Colors.transparent,
          side: BorderSide(
            color: colorScheme.onPrimary.withOpacity(1),
            width: 1.h,
          ),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(24.h),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      floatingActionButtonTheme: FloatingActionButtonThemeData(
        backgroundColor: colorScheme.primary,
      ),
      dividerTheme: DividerThemeData(
        thickness: 6,
        space: 6,
        color: colorScheme.onPrimaryContainer.withOpacity(1),
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        bodyLarge: TextStyle(
          color: appTheme.gray100,
          fontSize: 16.fSize,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w400,
        ),
        bodyMedium: TextStyle(
          color: appTheme.gray400,
          fontSize: 14.fSize,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w400,
        ),
        bodySmall: TextStyle(
          color: appTheme.blueGray500,
          fontSize: 12.fSize,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w400,
        ),
        displayLarge: TextStyle(
          color: appTheme.gray100,
          fontSize: 54.fSize,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w400,
        ),
        displaySmall: TextStyle(
          color: appTheme.gray100,
          fontSize: 36.fSize,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w400,
        ),
        headlineLarge: TextStyle(
          color: appTheme.gray100,
          fontSize: 32.fSize,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w600,
        ),
        headlineMedium: TextStyle(
          color: appTheme.limeA200,
          fontSize: 29.fSize,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w600,
        ),
        labelLarge: TextStyle(
          color: colorScheme.onPrimaryContainer.withOpacity(1),
          fontSize: 13.fSize,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w600,
        ),
        labelMedium: TextStyle(
          color: appTheme.blueGray100,
          fontSize: 10.fSize,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w600,
        ),
        titleLarge: TextStyle(
          color: appTheme.gray100,
          fontSize: 20.fSize,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w600,
        ),
        titleMedium: TextStyle(
          color: colorScheme.onPrimary.withOpacity(1),
          fontSize: 16.fSize,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w600,
        ),
        titleSmall: TextStyle(
          color: colorScheme.onPrimaryContainer.withOpacity(1),
          fontSize: 15.fSize,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w800,
        ),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0XFFD5D2FE),
    primaryContainer: Color(0XFF4D4D4D),
    secondary: Color(0XFF4D4D4D),
    secondaryContainer: Color(0X19FFFFFF),
    tertiary: Color(0XFF4D4D4D),
    tertiaryContainer: Color(0X19FFFFFF),

    // Background colors
    background: Color(0XFF4D4D4D),

    // Surface colors
    surface: Color(0XFF4D4D4D),
    surfaceTint: Color(0X6C262626),
    surfaceVariant: Color(0X19FFFFFF),

    // Error colors
    error: Color(0X6C262626),
    errorContainer: Color(0XFF9390BB),
    onError: Color(0X6CD5D2FE),
    onErrorContainer: Color(0X6C262626),

    // On colors(text colors)
    onBackground: Color(0X19FFFFFF),
    onInverseSurface: Color(0X6CD5D2FE),
    onPrimary: Color(0X6C262626),
    onPrimaryContainer: Color(0X19FFFFFF),
    onSecondary: Color(0X19FFFFFF),
    onSecondaryContainer: Color(0X6C262626),
    onTertiary: Color(0X19FFFFFF),
    onTertiaryContainer: Color(0X6C262626),

    // Other colors
    outline: Color(0X6C262626),
    outlineVariant: Color(0XFF4D4D4D),
    scrim: Color(0XFF4D4D4D),
    shadow: Color(0X6C262626),

    // Inverse colors
    inversePrimary: Color(0XFF4D4D4D),
    inverseSurface: Color(0X6C262626),

    // Pending colors
    onSurface: Color(0X19FFFFFF),
    onSurfaceVariant: Color(0X6C262626),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Black
  Color get black900 => Color(0XFF000000);

  // BlueGray
  Color get blueGray100 => Color(0XFFCCCCCC);
  Color get blueGray400 => Color(0XFF7F7CA4);
  Color get blueGray40001 => Color(0XFF888888);
  Color get blueGray500 => Color(0XFF6B688D);

  // Gray
  Color get gray100 => Color(0XFFF7F7F7);
  Color get gray400 => Color(0XFFB7B7B7);
  Color get gray500 => Color(0XFFA49A9A);
  Color get gray600 => Color(0XFF7A7A7A);
  Color get gray60001 => Color(0XFF717171);
  Color get gray700 => Color(0XFF666666);

  // LightGreen
  Color get lightGreen900 => Color(0XFF4F5508);
  Color get lightGreenA700 => Color(0XFF14FF00);

  // Lime
  Color get lime900 => Color(0XFF6F7711);
  Color get limeA200 => Color(0XFFF2FF53);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
